[build-system]
requires = ["setuptools>40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Repository = "https://github.com/codemouse92/textproof"
Issues = "https://github.com/codemouse92/textproof/issues"
Funding = "https://github.com/sponsors/CodeMouse92"

[project]
name = "textproof"
version = "1.0.0"
description = "Perform command-line spelling and grammar check on text."
readme = {file = "README.md", content-type = "text/markdown"}
license-files = ["LICENSE"]
authors = [
    {name = "Jason C. McDonald", email = "codemouse92@outlook.com"}
]
maintainers = [
    {name = "Jason C. McDonald", email = "codemouse92@outlook.com"}
]
keywords = ["proof", "spelling", "grammar", "utility"]

dependencies = [
    "requests >= 2.34.2",
    "click >= 8.4.2"
]
requires-python = ">=3.12, <4"

[project.optional-dependencies]
test = [
    "pytest",
    "coverage",
    "tox"
]

[project.scripts]
textproof = "textproof.__main__:main"

[tool.coverage.run]
source = [
    "textproof",
]

[tool.coverage.paths]
source = [
    "src/textproof",
    "**/site-packages/textproof"
]

[tool.mypy]
strict = true
enable_error_code = ["explicit-override"]

[tool.pytest.ini_options]
markers = [
    "typo_id: the example scenario number"
]

[tool.tox]
requires = ["tox>=4.9.0"]
envlist = ["py312", "py313", "py314", "py315"]
isolated_build = true

[tool.tox.env_run_base]
description = "Run test under {base_python}"
deps = ["pytest"]
commands = [["pytest"]]
